;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.byte 5
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,307,256

@instruments:
	.byte $30 ;instrument $03
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env5,@env0,@env0
	.byte $00
	.byte $30 ;instrument $07
	.word @env2,@env10,@env0
	.byte $00
	.byte $b0 ;instrument $08
	.word @env0,@env10,@env0
	.byte $00
	.byte $b0 ;instrument $09
	.word @env4,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $0a
	.word @env6,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $0b
	.word @env7,@env13,@env0
	.byte $00
	.byte $30 ;instrument $0d
	.word @env8,@env11,@env0
	.byte $00
	.byte $70 ;instrument $0f
	.word @env1,@env11,@env0
	.byte $00
	.byte $b0 ;instrument $19
	.word @env1,@env15,@env0
	.byte $00
	.byte $70 ;instrument $1c
	.word @env6,@env0,@env18
	.byte $00
	.byte $70 ;instrument $1d
	.word @env9,@env12,@env0
	.byte $00
	.byte $b0 ;instrument $1f
	.word @env9,@env16,@env0
	.byte $00
	.byte $30 ;instrument $20
	.word @env9,@env14,@env0
	.byte $00
	.byte $b0 ;instrument $21
	.word @env6,@env0,@env19
	.byte $00
	.byte $30 ;instrument $22
	.word @env9,@env14,@env0
	.byte $00
	.byte $30 ;instrument $23
	.word @env9,@env17,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$ce,$cd,$cc,$cb,$ca,$c9,$c1,$00,$07
@env2:
	.byte $cf,$cd,$cb,$c9,$c7,$c5,$c3,$c1,$c0,$00,$08
@env3:
	.byte $cb,$ca,$c8,$c7,$c5,$c4,$c3,$c1,$c0,$00,$08
@env4:
	.byte $c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$08
@env5:
	.byte $c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$08
@env6:
	.byte $c1,$c3,$c4,$c6,$c7,$c8,$c9,$ca,$ca,$cb,$cc,$cc,$cd,$0d,$cc,$cc
	.byte $cb,$ca,$c7,$c1,$00,$13
@env7:
	.byte $c2,$00,$00
@env8:
	.byte $cf,$00,$00
@env9:
	.byte $ce,$ce,$cd,$02,$cc,$04,$cb,$04,$ca,$03,$c9,$05,$c8,$06,$c7,$04
	.byte $c6,$06,$c5,$09,$c4,$08,$c3,$0c,$c2,$14,$c1,$1d,$c1,$00,$1c
@env10:
	.byte $c7,$c3,$c0,$bd,$00,$02
@env11:
	.byte $cc,$c0,$00,$01
@env12:
	.byte $be,$02,$bf,$c0,$00,$03
@env13:
	.byte $c0,$bf,$be,$bd,$bc,$bb,$ba,$b9,$b8,$b7,$b6,$b5,$b4,$b3,$b2,$b1
	.byte $b0,$af,$ae,$ad,$ac,$ab,$aa,$a9,$a8,$a7,$a6,$a5,$a4,$a3,$a2,$a1
	.byte $00,$1f
@env14:
	.byte $c0,$03,$c3,$03,$c7,$03,$c3,$02,$c3,$00,$00
@env15:
	.byte $c0,$c7,$c7,$c0,$00,$03
@env16:
	.byte $c0,$02,$c4,$02,$c9,$02,$c4,$c4,$c4,$00,$00
@env17:
	.byte $c0,$03,$c3,$03,$c8,$03,$c3,$02,$c3,$00,$00
@env18:
	.byte $c0,$bf,$bf,$c0,$00,$00
@env19:
	.byte $c0,$c1,$c2,$02,$c1,$c0,$c0,$c3,$c6,$c9,$cc,$cf,$02,$cf,$00,$00


@song0ch0:
	.byte $fb,$0c
@song0ch0loop:
@ref0:
	.byte $a0,$48,$9d,$52,$9d
@ref1:
	.byte $56,$bd
@ref2:
	.byte $48,$9d,$52,$9d
@ref3:
	.byte $56,$bd
@ref4:
	.byte $46,$8d,$44,$8d,$46,$8d,$42,$8d
@ref5:
	.byte $46,$95,$00,$a5
@ref6:
	.byte $a2,$46,$89,$5f,$a4,$44,$89,$5d,$a2,$46,$89,$5f,$a4,$42,$89,$5a
	.byte $81
@ref7:
	.byte $a2,$46,$89,$01,$98,$3d,$3d,$51,$4e,$a1
@ref8:
	.byte $9e,$30,$9d,$8c,$18,$89,$19,$18,$8d
	.byte $ff,$07
	.word @ref8
	.byte $ff,$07
	.word @ref8
	.byte $ff,$07
	.word @ref8
@ref12:
	.byte $9a,$2e,$ad,$8e,$34,$8d
@ref13:
	.byte $9a,$2e,$9d,$30,$8d,$34,$8d
@ref14:
	.byte $2e,$ad,$8e,$34,$8d
	.byte $ff,$06
	.word @ref13
@ref16:
	.byte $8e,$47,$90,$47,$9c,$34,$95,$8e,$47,$90,$47,$9c,$34,$85,$8e,$35
	.byte $90,$47,$9c,$34,$85
@ref17:
	.byte $8e,$47,$90,$47,$9c,$34,$85,$8e,$47,$90,$47,$9c,$34,$85,$8e,$48
	.byte $8d,$4c,$8d
@ref18:
	.byte $47,$90,$47,$9c,$34,$95,$8e,$47,$90,$47,$9c,$34,$85,$8e,$35,$90
	.byte $47,$9c,$34,$85
	.byte $ff,$0c
	.word @ref17
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref20:
	.byte $8e,$48,$83,$90,$48,$8e,$46,$83,$90,$46,$8e,$54,$83,$90,$54,$8e
	.byte $52,$83,$90,$52,$8e,$48,$83,$90,$48,$8e,$46,$83,$90,$46,$8e,$54
	.byte $83,$90,$54,$8e,$52,$83,$90,$52
	.byte $ff,$18
	.word @ref20
	.byte $ff,$18
	.word @ref20
	.byte $ff,$18
	.word @ref20
@ref24:
	.byte $8e,$47,$54,$87,$90,$54,$8e,$45,$54,$87,$90,$54,$8e,$47,$54,$87
	.byte $90,$54,$8e,$43,$52,$87,$90,$52
@ref25:
	.byte $8e,$47,$54,$87,$90,$54,$8e,$47,$55,$5b,$58,$a1
@ref26:
	.byte $47,$54,$87,$90,$54,$8e,$45,$54,$87,$90,$54,$8e,$47,$54,$87,$90
	.byte $54,$8e,$43,$52,$87,$90,$52
	.byte $ff,$09
	.word @ref25
@ref28:
	.byte $48,$83,$90,$48,$8e,$46,$83,$90,$46,$8e,$54,$83,$90,$54,$8e,$52
	.byte $83,$90,$52,$8e,$48,$83,$90,$48,$8e,$46,$83,$90,$46,$8e,$54,$83
	.byte $90,$54,$8e,$52,$83,$90,$52
	.byte $ff,$18
	.word @ref20
	.byte $ff,$18
	.word @ref20
	.byte $ff,$18
	.word @ref20
@ref32:
	.byte $8e,$4c,$bd
@ref33:
	.byte $54,$9d,$56,$9d
@ref34:
	.byte $4c,$bd
@ref35:
	.byte $54,$9d,$56,$9d
@ref36:
	.byte $4c,$bd
@ref37:
	.byte $54,$9d,$56,$9d
@ref38:
	.byte $4c,$bd
@ref39:
	.byte $54,$9d,$56,$9d
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref40:
	.byte $98,$30,$85,$01,$30,$00,$30,$85,$00,$85,$30,$85,$01,$30,$00,$30
	.byte $85,$01,$3a,$81
@ref41:
	.byte $30,$85,$01,$30,$00,$30,$85,$00,$85,$30,$85,$01,$30,$00,$30,$85
	.byte $00,$85
@ref42:
	.byte $30,$85,$01,$30,$00,$30,$85,$00,$85,$30,$85,$01,$30,$00,$30,$85
	.byte $01,$3a,$81
	.byte $ff,$12
	.word @ref41
@ref44:
	.byte $2e,$8d,$2c,$8d,$24,$8d,$22,$8d
@ref45:
	.byte $2e,$8d,$25,$2f,$2b,$28,$a1
	.byte $ff,$08
	.word @ref44
	.byte $ff,$07
	.word @ref45
	.byte $ff,$13
	.word @ref42
	.byte $ff,$12
	.word @ref41
	.byte $ff,$13
	.word @ref42
	.byte $ff,$12
	.word @ref41
@ref52:
	.byte $2e,$00,$2e,$00,$00,$2a,$00,$2e,$00,$2e,$00,$2a,$2e,$34,$34,$2a
	.byte $2e,$00,$2e,$00,$00,$2a,$00,$2e,$00,$2e,$00,$2a,$2e,$34,$34,$2a
@ref53:
	.byte $2e,$00,$2e,$00,$00,$2a,$00,$2e,$00,$2e,$00,$2a,$2e,$34,$34,$2a
	.byte $30,$00,$30,$00,$00,$2c,$00,$30,$00,$34,$00,$30,$34,$3a,$3a,$30
	.byte $ff,$20
	.word @ref52
	.byte $ff,$20
	.word @ref53
	.byte $ff,$20
	.word @ref52
	.byte $ff,$20
	.word @ref53
	.byte $ff,$20
	.word @ref52
	.byte $ff,$20
	.word @ref53
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref60:
	.byte $82,$20,$85,$88,$20,$85,$82,$20,$85,$88,$20,$85,$82,$20,$85,$88
	.byte $20,$85,$82,$20,$85,$88,$20,$85
@ref61:
	.byte $82,$20,$85,$88,$20,$85,$82,$20,$85,$88,$20,$85,$82,$20,$85,$88
	.byte $20,$85,$82,$21,$20,$20,$88,$21,$82,$20,$81
@ref62:
	.byte $20,$85,$88,$20,$85,$82,$20,$85,$88,$20,$85,$82,$20,$85,$88,$20
	.byte $85,$82,$20,$85,$88,$20,$85
	.byte $ff,$12
	.word @ref61
@ref64:
	.byte $20,$85,$88,$20,$85,$82,$20,$85,$88,$20,$85,$82,$20,$85,$88,$20
	.byte $85,$82,$21,$20,$20,$88,$20,$85
@ref65:
	.byte $82,$20,$85,$88,$20,$85,$09,$09,$82,$08,$08,$88,$09,$82,$20,$85
	.byte $88,$20,$85,$82,$21,$20,$20,$88,$21,$82,$20,$81
	.byte $ff,$11
	.word @ref64
	.byte $ff,$13
	.word @ref65
	.byte $ff,$10
	.word @ref62
	.byte $ff,$12
	.word @ref61
	.byte $ff,$11
	.word @ref64
	.byte $ff,$13
	.word @ref65
	.byte $ff,$10
	.word @ref62
	.byte $ff,$12
	.word @ref61
	.byte $ff,$10
	.word @ref62
	.byte $ff,$12
	.word @ref61
	.byte $ff,$10
	.word @ref62
	.byte $ff,$12
	.word @ref61
	.byte $ff,$10
	.word @ref62
	.byte $ff,$12
	.word @ref61
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref80:
	.byte $bf
@ref81:
	.byte $bf
@ref82:
	.byte $bf
@ref83:
	.byte $bf
@ref84:
	.byte $bf
@ref85:
	.byte $bf
@ref86:
	.byte $bf
@ref87:
	.byte $bf
@ref88:
	.byte $bf
@ref89:
	.byte $bf
@ref90:
	.byte $bf
@ref91:
	.byte $bf
@ref92:
	.byte $bf
@ref93:
	.byte $bf
@ref94:
	.byte $bf
@ref95:
	.byte $bf
@ref96:
	.byte $bf
@ref97:
	.byte $bf
@ref98:
	.byte $bf
@ref99:
	.byte $bf
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$0c
@song1ch0loop:
@ref100:
	.byte $8e,$36,$85,$34,$85,$36,$89,$3b,$3d,$3b,$37,$35,$36,$85,$32,$85
@ref101:
	.byte $3c,$85,$3a,$85,$3c,$89,$41,$45,$41,$3d,$3b,$3c,$85,$3a,$85
@ref102:
	.byte $36,$85,$3c,$85,$40,$85,$01,$45,$47,$45,$41,$3c,$81
@ref103:
	.byte $40,$85,$01,$41,$45,$41,$3d,$3b,$3c,$85,$3a,$85
@ref104:
	.byte $96,$4e,$9b,$00,$9f
@ref105:
	.byte $b7,$8e,$5d,$3c,$81
@ref106:
	.byte $1e,$85,$22,$85,$24,$85,$28,$85,$24,$85,$2c,$85,$1e,$85,$1c,$85
@ref107:
	.byte $1e,$85,$22,$85,$24,$85,$28,$85,$24,$85,$2c,$85,$1e,$85,$1a,$85
@ref108:
	.byte $36,$85,$44,$85,$40,$85,$3c,$85,$3a,$85,$32,$85,$3c,$85,$3a,$85
@ref109:
	.byte $44,$85,$3c,$85,$36,$85,$32,$85,$40,$85,$36,$85,$1e,$85,$2c,$85
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref110:
	.byte $92,$36,$3c,$44,$3c,$2c,$34,$3a,$34,$36,$3c,$44,$3c,$36,$85,$44
	.byte $85,$2c,$85,$36,$85,$33,$2e,$81
@ref111:
	.byte $3c,$44,$4a,$44,$32,$3a,$40,$3a,$3c,$44,$4a,$44,$3c,$85,$3c,$85
	.byte $44,$85,$36,$85,$2d,$34,$81
@ref112:
	.byte $36,$3c,$44,$3c,$36,$3c,$44,$3c,$40,$46,$4e,$46,$40,$85,$4e,$85
	.byte $46,$85
@ref113:
	.byte $2c,$34,$3a,$34,$2c,$85,$2c,$34,$3a,$34,$2c,$34,$3a,$34,$2c,$34
	.byte $3a,$34,$2c,$34,$3a,$34
@ref114:
	.byte $94,$36,$3c,$40,$44,$36,$3c,$40,$44,$40,$46,$4e,$58,$40,$46,$4e
	.byte $58,$3c,$44,$4e,$54,$3c,$44,$4e,$54,$40,$48,$4e,$58,$44,$52,$5c
	.byte $64
@ref115:
	.byte $36,$3c,$40,$44,$36,$3c,$40,$44,$40,$46,$4e,$58,$40,$46,$4e,$58
	.byte $3c,$44,$4e,$54,$36,$44,$54,$4e,$40,$48,$4e,$58,$44,$52,$5c,$64
@ref116:
	.byte $92,$4e,$44,$4e,$52,$52,$44,$4e,$52,$54,$44,$52,$54,$58,$4a,$52
	.byte $58,$5c,$44,$52,$5c,$52,$44,$4c,$52,$4e,$85,$4c,$85
@ref117:
	.byte $4e,$44,$4e,$52,$52,$44,$4e,$52,$54,$44,$52,$54,$58,$4a,$54,$58
	.byte $5c,$44,$52,$5c,$52,$44,$4c,$52,$4e,$85,$4a,$85
@ref118:
	.byte $94,$5c,$54,$58,$5c,$5c,$54,$58,$5c,$5e,$87,$4a,$58,$5e,$58,$52
	.byte $54,$58,$58,$52,$54,$58,$5c,$58,$54,$52,$4e,$4c,$48,$4c
@ref119:
	.byte $4e,$44,$4e,$52,$52,$44,$4e,$52,$54,$44,$52,$54,$58,$4a,$52,$54
	.byte $58,$5c,$44,$52,$5c,$5c,$64,$6a,$66,$8d
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref120:
	.byte $8c,$36,$85,$2c,$85,$98,$36,$85,$00,$85,$8c,$36,$85,$2c,$85,$36
	.byte $85,$33,$3a,$81
@ref121:
	.byte $3c,$85,$32,$85,$98,$3c,$85,$00,$85,$8c,$3c,$85,$2c,$85,$36,$85
	.byte $34,$85
@ref122:
	.byte $36,$85,$2c,$85,$98,$28,$85,$00,$85,$8c,$2e,$85,$36,$85
@ref123:
	.byte $98,$34,$85,$00,$85,$34,$8d,$34,$8d
@ref124:
	.byte $36,$85,$36,$85,$40,$85,$40,$85,$3c,$85,$3c,$85,$44,$85,$3c,$85
	.byte $ff,$10
	.word @ref124
@ref126:
	.byte $8c,$36,$85,$3a,$85,$3c,$85,$40,$85,$44,$85,$2c,$85,$36,$85,$2c
	.byte $85
@ref127:
	.byte $36,$85,$3a,$85,$3c,$85,$40,$85,$44,$85,$2c,$85,$36,$85,$32,$85
@ref128:
	.byte $98,$36,$85,$44,$85,$40,$46,$4f,$40,$85,$32,$85,$3a,$85,$3c,$85
	.byte $3a,$85
@ref129:
	.byte $36,$85,$44,$85,$36,$85,$44,$85,$46,$85,$2c,$85,$36,$85,$44,$85
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref130:
	.byte $bf
@ref131:
	.byte $bf
@ref132:
	.byte $af
@ref133:
	.byte $af
@ref134:
	.byte $bf
@ref135:
	.byte $bf
@ref136:
	.byte $bf
@ref137:
	.byte $bf
@ref138:
	.byte $bf
@ref139:
	.byte $bf
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref140:
	.byte $bf
@ref141:
	.byte $bf
@ref142:
	.byte $af
@ref143:
	.byte $af
@ref144:
	.byte $bf
@ref145:
	.byte $bf
@ref146:
	.byte $bf
@ref147:
	.byte $bf
@ref148:
	.byte $bf
@ref149:
	.byte $bf
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$07
@ref150:
	.byte $a2,$40,$8d,$32,$8d,$44,$9d,$00,$9d
@song2ch0loop:
@ref151:
	.byte $81
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@ref152:
	.byte $98,$41,$41,$37,$2f,$33,$39,$41,$39,$80,$33,$82,$33,$84,$33,$86
	.byte $33,$33,$00,$a9
@song2ch1loop:
@ref153:
	.byte $81
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@ref154:
	.byte $98,$40,$85,$2e,$85,$32,$85,$38,$85,$2c,$95,$00,$a5
@song2ch2loop:
@ref155:
	.byte $81
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@ref156:
	.byte $df
@song2ch3loop:
@ref157:
	.byte $81
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@ref158:
	.byte $df
@song2ch4loop:
@ref159:
	.byte $81
	.byte $fd
	.word @song2ch4loop


@song3ch0:
	.byte $fb,$05
@ref160:
	.byte $80,$2d,$82,$2d,$84,$2d,$86,$2c,$89,$80,$2d,$82,$2d,$84,$2d,$86
	.byte $2c,$89,$80,$2d,$82,$2d,$84,$2d,$80,$2d,$82,$2d,$84,$2d,$80,$2d
	.byte $82,$2d,$84,$2d,$a2,$2c,$a9
@song3ch0loop:
@ref161:
	.byte $f9,$85
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@ref162:
	.byte $80,$3b,$82,$3b,$84,$3b,$86,$3a,$89,$80,$3b,$82,$3b,$84,$3b,$86
	.byte $3a,$89,$80,$3b,$82,$3b,$84,$3b,$80,$3b,$82,$3b,$84,$3b,$80,$3b
	.byte $82,$3b,$84,$3b,$a2,$44,$a9
@song3ch1loop:
@ref163:
	.byte $f9,$85
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@ref164:
	.byte $98,$45,$2d,$3b,$45,$00,$85,$45,$2d,$3b,$45,$00,$85,$45,$2d,$33
	.byte $3b,$45,$4b,$45,$2d,$33,$45,$00,$85,$00,$9d
@song3ch2loop:
@ref165:
	.byte $f9,$85
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@ref166:
	.byte $88,$11,$11,$11,$10,$89,$11,$11,$11,$10,$89,$11,$11,$11,$11,$11
	.byte $11,$11,$11,$11,$10,$a9
@song3ch3loop:
@ref167:
	.byte $f9,$85
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@ref168:
	.byte $f9,$85
@song3ch4loop:
@ref169:
	.byte $f9,$85
	.byte $fd
	.word @song3ch4loop


@song4ch0:
	.byte $fb,$0a
@song4ch0loop:
@ref170:
	.byte $80,$3a,$84,$3a,$83,$80,$3c,$84,$3c,$80,$3a,$84,$3a,$80,$36,$84
	.byte $36,$83,$80,$32,$84,$32,$80,$30,$84,$30,$80,$32,$84,$32,$8b,$80
	.byte $36,$84,$36,$83,$80,$30,$84,$30,$80,$28,$84,$28
@ref171:
	.byte $80,$3a,$84,$3a,$83,$80,$3c,$84,$3c,$80,$40,$84,$40,$80,$36,$84
	.byte $36,$83,$80,$32,$84,$32,$80,$30,$84,$30,$80,$32,$84,$32,$8b,$80
	.byte $36,$84,$36,$8b
	.byte $ff,$18
	.word @ref170
	.byte $ff,$14
	.word @ref171
@ref174:
	.byte $80,$32,$84,$32,$83,$80,$3a,$84,$3a,$80,$40,$84,$40,$80,$3e,$84
	.byte $3e,$83,$80,$40,$84,$40,$80,$44,$84,$44,$80,$48,$84,$48,$80,$4a
	.byte $84,$4a,$80,$48,$84,$48,$80,$44,$84,$44,$80,$40,$84,$40,$83,$80
	.byte $3a,$84,$3a,$83
@ref175:
	.byte $80,$3a,$84,$3a,$83,$80,$3e,$84,$3e,$80,$40,$84,$40,$80,$3e,$84
	.byte $3e,$83,$80,$44,$84,$44,$83,$80,$48,$84,$48,$80,$4a,$84,$4a,$80
	.byte $4e,$84,$4e,$80,$4a,$84,$4a,$80,$48,$84,$48,$83,$80,$40,$84,$40
	.byte $83
	.byte $ff,$1c
	.word @ref174
@ref177:
	.byte $80,$3a,$84,$3a,$83,$80,$3e,$84,$3e,$80,$40,$84,$40,$80,$3e,$84
	.byte $3e,$83,$80,$44,$84,$44,$83,$80,$40,$84,$40,$86,$40,$99
	.byte $fd
	.word @song4ch0loop

@song4ch1:
@song4ch1loop:
@ref178:
	.byte $8c,$3b,$3b,$3b,$3b,$37,$37,$37,$37,$33,$33,$33,$33,$31,$31,$31
	.byte $30,$81
@ref179:
	.byte $3b,$3b,$3b,$3b,$37,$37,$37,$37,$33,$33,$33,$33,$31,$31,$31,$30
	.byte $81
	.byte $ff,$11
	.word @ref179
	.byte $ff,$11
	.word @ref179
@ref182:
	.byte $3b,$3b,$3b,$3b,$37,$37,$37,$37,$31,$31,$31,$31,$31,$31,$31,$30
	.byte $81
@ref183:
	.byte $3b,$3b,$41,$41,$3f,$3f,$45,$45,$49,$49,$49,$49,$49,$49,$49,$48
	.byte $81
	.byte $ff,$11
	.word @ref182
	.byte $ff,$11
	.word @ref183
	.byte $fd
	.word @song4ch1loop

@song4ch2:
@song4ch2loop:
@ref186:
	.byte $98,$32,$8d,$28,$8d,$2c,$8d,$28,$8d
@ref187:
	.byte $32,$8d,$28,$8d,$2c,$8d,$28,$8d
	.byte $ff,$08
	.word @ref187
	.byte $ff,$08
	.word @ref187
@ref190:
	.byte $32,$8d,$36,$8d,$40,$8d,$3a,$8d
@ref191:
	.byte $32,$8d,$36,$8d,$40,$8d,$40,$8d
	.byte $ff,$08
	.word @ref190
	.byte $ff,$08
	.word @ref191
	.byte $fd
	.word @song4ch2loop

@song4ch3:
@song4ch3loop:
@ref194:
	.byte $80,$08,$85,$88,$08,$85,$80,$08,$85,$88,$08,$85,$80,$08,$85,$88
	.byte $08,$85,$80,$08,$85,$88,$08,$85
	.byte $ff,$10
	.word @ref194
	.byte $ff,$10
	.word @ref194
	.byte $ff,$10
	.word @ref194
	.byte $ff,$10
	.word @ref194
	.byte $ff,$10
	.word @ref194
	.byte $ff,$10
	.word @ref194
	.byte $ff,$10
	.word @ref194
	.byte $fd
	.word @song4ch3loop

@song4ch4:
@song4ch4loop:
@ref202:
	.byte $bf
@ref203:
	.byte $bf
@ref204:
	.byte $bf
@ref205:
	.byte $bf
@ref206:
	.byte $bf
@ref207:
	.byte $bf
@ref208:
	.byte $bf
@ref209:
	.byte $bf
	.byte $fd
	.word @song4ch4loop
