// Tileset pals generated by mkts [nes mode]
// Copyleft 2016 The Mojon Twins
 
const unsigned char ts_pals [] = {
	 0,  3,  2,  0,  3,  3,  3,  1,  2,  3,  1,  0,  3,  2,  1,  0, 
	 0,  0,  0,  0,  1,  2,  2,  1,  1,  1,  1,  1,  1,  1,  0,  0, 
	 0,  1,  2,  3,  3,  3,  1,  1,  1,  1,  1,  1,  0,  1,  1,  0, 
};
